### ISSUE TITLE
On 'nerd publish', cannot select a specific Azure Subscription

### ISSUE THREAD

**Issue by MisterPhoton** [NERDStack/nerd-cli#25]
I have multiple subscriptions for different clients accessible through a single Azure login account.

When I run 'nerd publish', I get to the Azure CLI login and login successfully, but can't select the correct subscription for publication.

Is there a way to pre-set the target subscription, or to select it during the 'nerd publish' command?

**Comment by tripdubroot** [comment]
@tstringer I think the right way to handle this is to provide the ability for the use to choose the interactive login (username/password) or to use an SPN.  We would then prompt for the SPN creds: https://github.com/Azure/azure-sdk-for-node/blob/master/Documentation/Authentication.md#service-principal-authentication

**Comment by ianchamb** [comment]
Hi there - Ian Chamberlain, the project manager here.  We wanted to check in and see if there has been any progress on solving this issue.  Thanks for your help!

**Comment by tripdubroot** [comment]
@ianchamb I've just pushed a PR for Tom to test... If it works, we should be good to go.

**Comment by ianchamb** [comment]
@tstringer @tripdubroot  thanks guys - fingers crossed

**Comment by ianphil** [comment]
@ianchamb The changes have been merged. @tstringer will close this issue once it's published to NPM.

**Comment by ianphil** [comment]
@ianchamb This is published to NPM registry now. You should be able to install v0.5.0 and select from your subscriptions.
