### ISSUE TITLE
Need to resolve discrepancy between Windows and Mac/Linux install

### ISSUE THREAD

**Issue by jplane** [NERDStack/nerd-cli#6]
The code in run.js needs to use "npm run start-local-win" on Windows machines

**Comment by jplane** [comment]
also need to ensure DocDB creds propagate to the PS script in the case of a Windows install

**Comment by tstringer** [comment]
Added! 👍  😄  https://github.com/NERDStack/nerd-cli/blob/master/src/post-install.js#L60-L84
